// Top-100 liquid U.S. names + a few mega-caps abroad.
// Alphabetical for easy “startsWith” filtering.
export const POPULAR_SYMBOLS: { symbol: string; name: string }[] = [
    { symbol: 'AAPL', name: 'Apple Inc.' },
    { symbol: 'ABT',  name: 'Abbott Laboratories' },
    { symbol: 'ADBE', name: 'Adobe Inc.' },
    { symbol: 'AMD',  name: 'Advanced Micro Devices' },
    { symbol: 'AMGN', name: 'Amgen Inc.' },
    { symbol: 'AMZN', name: 'Amazon.com Inc.' },
    { symbol: 'AVGO', name: 'Broadcom Inc.' },
    { symbol: 'AXP',  name: 'American Express' },
    { symbol: 'BA',   name: 'Boeing Co.' },
    { symbol: 'BAC',  name: 'Bank of America' },
    { symbol: 'BMY',  name: 'Bristol-Myers Squibb' },
    { symbol: 'BRK.B',name: 'Berkshire Hathaway B' },
    { symbol: 'CAT',  name: 'Caterpillar Inc.' },
    { symbol: 'CMCSA',name: 'Comcast Corp.' },
    { symbol: 'COST', name: 'Costco Wholesale' },
    { symbol: 'CRM',  name: 'Salesforce Inc.' },
    { symbol: 'CSCO', name: 'Cisco Systems' },
    { symbol: 'CVS',  name: 'CVS Health' },
    { symbol: 'CVX',  name: 'Chevron Corp.' },
    { symbol: 'DIS',  name: 'Walt Disney Co.' },
    { symbol: 'DUK',  name: 'Duke Energy' },
    { symbol: 'EMR',  name: 'Emerson Electric' },
    { symbol: 'F',    name: 'Ford Motor' },
    { symbol: 'FDX',  name: 'FedEx Corp.' },
    { symbol: 'GE',   name: 'General Electric' },
    { symbol: 'GILD', name: 'Gilead Sciences' },
    { symbol: 'GOOGL',name: 'Alphabet Class A' },
    { symbol: 'HD',   name: 'Home Depot' },
    { symbol: 'HON',  name: 'Honeywell Intl.' },
    { symbol: 'IBM',  name: 'IBM Corp.' },
    { symbol: 'INTC', name: 'Intel Corp.' },
    { symbol: 'JNJ',  name: 'Johnson & Johnson' },
    { symbol: 'JPM',  name: 'JPMorgan Chase' },
    { symbol: 'KO',   name: 'Coca-Cola Co.' },
    { symbol: 'LLY',  name: 'Eli Lilly & Co.' },
    { symbol: 'LMT',  name: 'Lockheed Martin' },
    { symbol: 'LOW',  name: 'Lowe’s Companies' },
    { symbol: 'MA',   name: 'Mastercard Inc.' },
    { symbol: 'MCD',  name: 'McDonald’s Corp.' },
    { symbol: 'MDLZ', name: 'Mondelez International' },
    { symbol: 'META', name: 'Meta Platforms' },
    { symbol: 'MMM',  name: '3M Co.' },
    { symbol: 'MRK',  name: 'Merck & Co.' },
    { symbol: 'MS',   name: 'Morgan Stanley' },
    { symbol: 'MSFT', name: 'Microsoft Corp.' },
    { symbol: 'NKE',  name: 'Nike Inc.' },
    { symbol: 'NVDA', name: 'NVIDIA Corp.' },
    { symbol: 'ORCL', name: 'Oracle Corp.' },
    { symbol: 'PEP',  name: 'PepsiCo Inc.' },
    { symbol: 'PFE',  name: 'Pfizer Inc.' },
    { symbol: 'PG',   name: 'Procter & Gamble' },
    { symbol: 'PM',   name: 'Philip Morris Intl.' },
    { symbol: 'PYPL', name: 'PayPal Holdings' },
    { symbol: 'QCOM', name: 'Qualcomm Inc.' },
    { symbol: 'RTX',  name: 'RTX Corporation' },
    { symbol: 'SBUX', name: 'Starbucks Corp.' },
    { symbol: 'SCHW', name: 'Charles Schwab' },
    { symbol: 'SO',   name: 'Southern Company' },
    { symbol: 'SPGI', name: 'S&P Global Inc.' },
    { symbol: 'T',    name: 'AT&T Inc.' },
    { symbol: 'TGT',  name: 'Target Corp.' },
    { symbol: 'TMO',  name: 'Thermo Fisher' },
    { symbol: 'TSLA', name: 'Tesla Inc.' },
    { symbol: 'TXN',  name: 'Texas Instruments' },
    { symbol: 'UNH',  name: 'UnitedHealth Group' },
    { symbol: 'UNP',  name: 'Union Pacific' },
    { symbol: 'UPS',  name: 'United Parcel Service' },
    { symbol: 'USB',  name: 'U.S. Bancorp' },
    { symbol: 'V',    name: 'Visa Inc.' },
    { symbol: 'VZ',   name: 'Verizon Communications' },
    { symbol: 'WBA',  name: 'Walgreens Boots Alliance' },
    { symbol: 'WFC',  name: 'Wells Fargo' },
    { symbol: 'WMT',  name: 'Walmart Inc.' },
    { symbol: 'XOM',  name: 'Exxon Mobil' },
    /* —— expand up to ~100 as desired —— */
  ];
  