export const POPULAR_SYMBOLS: { symbol: string; name: string; sector?: string }[] = [
    { symbol: "A", name: "Agilent Technologies, Inc.", sector: "Healthcare" },
    { symbol: "AAPL", name: "Apple Inc.", sector: "Technology" },
    { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
    { symbol: "ABNB", name: "Airbnb, Inc.", sector: "Consumer Cyclical" },
    { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
    { symbol: "ACGL", name: "Arch Capital Group Ltd.", sector: "Financial Services" },
    { symbol: "ACN", name: "Accenture plc", sector: "Technology" },
    { symbol: "ADBE", name: "Adobe Inc.", sector: "Technology" },
    { symbol: "ADI", name: "Analog Devices, Inc.", sector: "Technology" },
    { symbol: "ADM", name: "Archer-Daniels-Midland Company", sector: "Consumer Defensive" },
    { symbol: "ADP", name: "Automatic Data Processing, Inc.", sector: "Technology" },
    { symbol: "ADSK", name: "Autodesk, Inc.", sector: "Technology" },
    { symbol: "AEE", name: "Ameren Corporation", sector: "Utilities" },
    { symbol: "AEP", name: "American Electric Power Company", sector: "Utilities" },
    { symbol: "AES", name: "The AES Corporation", sector: "Utilities" },
    { symbol: "AFL", name: "AFLAC Incorporated", sector: "Financial Services" },
    { symbol: "AIG", name: "American International Group, I", sector: "Financial Services" },
    { symbol: "AIZ", name: "Assurant, Inc.", sector: "Financial Services" },
    { symbol: "AJG", name: "Arthur J. Gallagher & Co.", sector: "Financial Services" },
    { symbol: "AKAM", name: "Akamai Technologies, Inc.", sector: "Technology" },
    { symbol: "ALB", name: "Albemarle Corporation", sector: "Basic Materials" },
    { symbol: "ALGN", name: "Align Technology, Inc.", sector: "Healthcare" },
    { symbol: "ALL", name: "Allstate Corporation (The)", sector: "Financial Services" },
    { symbol: "ALLE", name: "Allegion plc", sector: "Industrials" },
    { symbol: "AMAT", name: "Applied Materials, Inc.", sector: "Technology" },
    { symbol: "AMCR", name: "Amcor plc", sector: "Consumer Cyclical" },
    { symbol: "AMD", name: "Advanced Micro Devices, Inc.", sector: "Technology" },
    { symbol: "AME", name: "AMETEK, Inc.", sector: "Industrials" },
    { symbol: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
    { symbol: "AMP", name: "Ameriprise Financial, Inc.", sector: "Financial Services" },
    { symbol: "AMT", name: "American Tower Corporation (REI", sector: "Real Estate" },
    { symbol: "AMTM", name: "Amentum Holdings, Inc.", sector: "Industrials" },
    { symbol: "AMZN", name: "Amazon.com, Inc.", sector: "Consumer Cyclical" },
    { symbol: "ANET", name: "Arista Networks, Inc.", sector: "Technology" },
    { symbol: "ANSS", name: "ANSYS, Inc.", sector: "Technology" },
    { symbol: "AON", name: "Aon plc", sector: "Financial Services" },
    { symbol: "AOS", name: "A.O. Smith Corporation", sector: "Industrials" },
    { symbol: "APA", name: "APA Corporation", sector: "Energy" },
    { symbol: "APD", name: "Air Products and Chemicals, Inc", sector: "Basic Materials" },
    { symbol: "APH", name: "Amphenol Corporation", sector: "Technology" },
    { symbol: "APTV", name: "Aptiv PLC", sector: "Consumer Cyclical" },
    { symbol: "ARE", name: "Alexandria Real Estate Equities", sector: "Real Estate" },
    { symbol: "ATO", name: "Atmos Energy Corporation", sector: "Utilities" },
    { symbol: "AVB", name: "AvalonBay Communities, Inc.", sector: "Real Estate" },
    { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
    { symbol: "AVY", name: "Avery Dennison Corporation", sector: "Consumer Cyclical" },
    { symbol: "AWK", name: "American Water Works Company, I", sector: "Utilities" },
    { symbol: "AXON", name: "Axon Enterprise, Inc.", sector: "Industrials" },
    { symbol: "AXP", name: "American Express Company", sector: "Financial Services" },
    { symbol: "AZO", name: "AutoZone, Inc.", sector: "Consumer Cyclical" },
    { symbol: "BA", name: "Boeing Company (The)", sector: "Industrials" },
    { symbol: "BAC", name: "Bank of America Corporation", sector: "Financial Services" },
    { symbol: "BALL", name: "Ball Corporation", sector: "Consumer Cyclical" },
    { symbol: "BAX", name: "Baxter International Inc.", sector: "Healthcare" },
    { symbol: "BBY", name: "Best Buy Co., Inc.", sector: "Consumer Cyclical" },
    { symbol: "BDX", name: "Becton, Dickinson and Company", sector: "Healthcare" },
    { symbol: "BEN", name: "Franklin Resources, Inc.", sector: "Financial Services" },
    { symbol: "BF-B", name: "Brown Forman Inc", sector: "Consumer Defensive" },
    { symbol: "BG", name: "Bunge Limited", sector: "Consumer Defensive" },
    { symbol: "BIIB", name: "Biogen Inc.", sector: "Healthcare" },
    { symbol: "BK", name: "The Bank of New York Mellon Cor", sector: "Financial Services" },
    { symbol: "BKNG", name: "Booking Holdings Inc. Common St", sector: "Consumer Cyclical" },
    { symbol: "BKR", name: "Baker Hughes Company", sector: "Energy" },
    { symbol: "BLDR", name: "Builders FirstSource, Inc.", sector: "Industrials" },
    { symbol: "BLK", name: "BlackRock, Inc.", sector: "Financial Services" },
    { symbol: "BMY", name: "Bristol-Myers Squibb Company", sector: "Healthcare" },
    { symbol: "BR", name: "Broadridge Financial Solutions,", sector: "Technology" },
    { symbol: "BRK-B", name: "Berkshire Hathaway Inc. New", sector: "Financial Services" },
    { symbol: "BRO", name: "Brown & Brown, Inc.", sector: "Financial Services" },
    { symbol: "BSX", name: "Boston Scientific Corporation", sector: "Healthcare" },
    { symbol: "BWA", name: "BorgWarner Inc.", sector: "Consumer Cyclical" },
    { symbol: "BX", name: "Blackstone Inc.", sector: "Financial Services" },
    { symbol: "BXP", name: "BXP, Inc.", sector: "Real Estate" },
    { symbol: "C", name: "Citigroup, Inc.", sector: "Financial Services" },
    { symbol: "CAG", name: "ConAgra Brands, Inc.", sector: "Consumer Defensive" },
    { symbol: "CAH", name: "Cardinal Health, Inc.", sector: "Healthcare" },
    { symbol: "CARR", name: "Carrier Global Corporation", sector: "Industrials" },
    { symbol: "CAT", name: "Caterpillar, Inc.", sector: "Industrials" },
    { symbol: "CB", name: "Chubb Limited", sector: "Financial Services" },
    { symbol: "CBOE", name: "Cboe Global Markets, Inc.", sector: "Financial Services" },
    { symbol: "CBRE", name: "CBRE Group Inc", sector: "Real Estate" },
    { symbol: "CCI", name: "Crown Castle Inc.", sector: "Real Estate" },
    { symbol: "CCL", name: "Carnival Corporation", sector: "Consumer Cyclical" },
    { symbol: "CDNS", name: "Cadence Design Systems, Inc.", sector: "Technology" },
    { symbol: "CDW", name: "CDW Corporation", sector: "Technology" },
    { symbol: "CE", name: "Celanese Corporation", sector: "Basic Materials" },
    { symbol: "CEG", name: "Constellation Energy Corporatio", sector: "Utilities" },
    { symbol: "CF", name: "CF Industries Holdings, Inc.", sector: "Basic Materials" },
    { symbol: "CFG", name: "Citizens Financial Group, Inc.", sector: "Financial Services" },
    { symbol: "CHD", name: "Church & Dwight Company, Inc.", sector: "Consumer Defensive" },
    { symbol: "CHRW", name: "C.H. Robinson Worldwide, Inc.", sector: "Industrials" },
    { symbol: "CHTR", name: "Charter Communications, Inc.", sector: "Communication Services" },
    { symbol: "CI", name: "The Cigna Group", sector: "Healthcare" },
    { symbol: "CINF", name: "Cincinnati Financial Corporatio", sector: "Financial Services" },
    { symbol: "CL", name: "Colgate-Palmolive Company", sector: "Consumer Defensive" },
    { symbol: "CLX", name: "Clorox Company (The)", sector: "Consumer Defensive" },
    { symbol: "CMCSA", name: "Comcast Corporation", sector: "Communication Services" },
    { symbol: "CME", name: "CME Group Inc.", sector: "Financial Services" },
    { symbol: "CMG", name: "Chipotle Mexican Grill, Inc.", sector: "Consumer Cyclical" },
    { symbol: "CMI", name: "Cummins Inc.", sector: "Industrials" },
    { symbol: "CMS", name: "CMS Energy Corporation", sector: "Utilities" },
    { symbol: "CNC", name: "Centene Corporation", sector: "Healthcare" },
    { symbol: "CNP", name: "CenterPoint Energy, Inc (Holdin", sector: "Utilities" },
    { symbol: "COF", name: "Capital One Financial Corporati", sector: "Financial Services" },
    { symbol: "COO", name: "The Cooper Companies, Inc.", sector: "Healthcare" },
    { symbol: "COP", name: "ConocoPhillips", sector: "Energy" },
    { symbol: "COR", name: "Cencora, Inc.", sector: "Healthcare" },
    { symbol: "COST", name: "Costco Wholesale Corporation", sector: "Consumer Defensive" },
    { symbol: "CPAY", name: "Corpay, Inc.", sector: "Technology" },
    { symbol: "CPB", name: "The Campbell's Company", sector: "Consumer Defensive" },
    { symbol: "CPRT", name: "Copart, Inc.", sector: "Industrials" },
    { symbol: "CPT", name: "Camden Property Trust", sector: "Real Estate" },
    { symbol: "CRL", name: "Charles River Laboratories Inte", sector: "Healthcare" },
    { symbol: "CRM", name: "Salesforce, Inc.", sector: "Technology" },
    { symbol: "CRWD", name: "CrowdStrike Holdings, Inc.", sector: "Technology" },
    { symbol: "CSCO", name: "Cisco Systems, Inc.", sector: "Technology" },
    { symbol: "CSGP", name: "CoStar Group, Inc.", sector: "Real Estate" },
    { symbol: "CSX", name: "CSX Corporation", sector: "Industrials" },
    { symbol: "CTAS", name: "Cintas Corporation", sector: "Industrials" },
    { symbol: "CTRA", name: "Coterra Energy Inc.", sector: "Energy" },
    { symbol: "CTSH", name: "Cognizant Technology Solutions ", sector: "Technology" },
    { symbol: "CTVA", name: "Corteva, Inc.", sector: "Basic Materials" },
    { symbol: "CVS", name: "CVS Health Corporation", sector: "Healthcare" },
    { symbol: "CVX", name: "Chevron Corporation", sector: "Energy" },
    { symbol: "CZR", name: "Caesars Entertainment, Inc.", sector: "Consumer Cyclical" },
    { symbol: "D", name: "Dominion Energy, Inc.", sector: "Utilities" },
    { symbol: "DAL", name: "Delta Air Lines, Inc.", sector: "Industrials" },
    { symbol: "DAY", name: "Dayforce, Inc.", sector: "Technology" },
    { symbol: "DD", name: "DuPont de Nemours, Inc.", sector: "Basic Materials" },
    { symbol: "DE", name: "Deere & Company", sector: "Industrials" },
    { symbol: "DECK", name: "Deckers Outdoor Corporation", sector: "Consumer Cyclical" },
    { symbol: "DELL", name: "Dell Technologies Inc.", sector: "Technology" },
    { symbol: "DFS", name: "Discover Financial Services", sector: "Financial Services" },
    { symbol: "DG", name: "Dollar General Corporation", sector: "Consumer Defensive" },
    { symbol: "DGX", name: "Quest Diagnostics Incorporated", sector: "Healthcare" },
    { symbol: "DHI", name: "D.R. Horton, Inc.", sector: "Consumer Cyclical" },
    { symbol: "DHR", name: "Danaher Corporation", sector: "Healthcare" },
    { symbol: "DIS", name: "Walt Disney Company (The)", sector: "Communication Services" },
    { symbol: "DLR", name: "Digital Realty Trust, Inc.", sector: "Real Estate" },
    { symbol: "DLTR", name: "Dollar Tree, Inc.", sector: "Consumer Defensive" },
    { symbol: "DOC", name: "Healthpeak Properties, Inc.", sector: "Real Estate" },
    { symbol: "DOV", name: "Dover Corporation", sector: "Industrials" },
    { symbol: "DOW", name: "Dow Inc.", sector: "Basic Materials" },
    { symbol: "DPZ", name: "Domino's Pizza Inc", sector: "Consumer Cyclical" },
    { symbol: "DRI", name: "Darden Restaurants, Inc.", sector: "Consumer Cyclical" },
    { symbol: "DTE", name: "DTE Energy Company", sector: "Utilities" },
    { symbol: "DUK", name: "Duke Energy Corporation (Holdin", sector: "Utilities" },
    { symbol: "DVA", name: "DaVita Inc.", sector: "Healthcare" },
    { symbol: "DVN", name: "Devon Energy Corporation", sector: "Energy" },
    { symbol: "DXCM", name: "DexCom, Inc.", sector: "Healthcare" },
    { symbol: "EA", name: "Electronic Arts Inc.", sector: "Communication Services" },
    { symbol: "EBAY", name: "eBay Inc.", sector: "Consumer Cyclical" },
    { symbol: "ECL", name: "Ecolab Inc.", sector: "Basic Materials" },
    { symbol: "ED", name: "Consolidated Edison, Inc.", sector: "Utilities" },
    { symbol: "EFX", name: "Equifax, Inc.", sector: "Industrials" },
    { symbol: "EG", name: "Everest Group, Ltd.", sector: "Financial Services" },
    { symbol: "EIX", name: "Edison International", sector: "Utilities" },
    { symbol: "EL", name: "Estee Lauder Companies, Inc. (T", sector: "Consumer Defensive" },
    { symbol: "ELV", name: "Elevance Health, Inc.", sector: "Healthcare" },
    { symbol: "EMN", name: "Eastman Chemical Company", sector: "Basic Materials" },
    { symbol: "EMR", name: "Emerson Electric Company", sector: "Industrials" },
    { symbol: "ENPH", name: "Enphase Energy, Inc.", sector: "Technology" },
    { symbol: "EOG", name: "EOG Resources, Inc.", sector: "Energy" },
    { symbol: "EPAM", name: "EPAM Systems, Inc.", sector: "Technology" },
    { symbol: "EQIX", name: "Equinix, Inc.", sector: "Real Estate" },
    { symbol: "EQR", name: "Equity Residential", sector: "Real Estate" },
    { symbol: "EQT", name: "EQT Corporation", sector: "Energy" },
    { symbol: "ERIE", name: "Erie Indemnity Company", sector: "Financial Services" },
    { symbol: "ES", name: "Eversource Energy (D/B/A)", sector: "Utilities" },
    { symbol: "ESS", name: "Essex Property Trust, Inc.", sector: "Real Estate" },
    { symbol: "ETN", name: "Eaton Corporation, PLC", sector: "Industrials" },
    { symbol: "ETR", name: "Entergy Corporation", sector: "Utilities" },
    { symbol: "EVRG", name: "Evergy, Inc.", sector: "Utilities" },
    { symbol: "EW", name: "Edwards Lifesciences Corporatio", sector: "Healthcare" },
    { symbol: "EXC", name: "Exelon Corporation", sector: "Utilities" },
    { symbol: "EXPD", name: "Expeditors International of Was", sector: "Industrials" },
    { symbol: "EXPE", name: "Expedia Group, Inc.", sector: "Consumer Cyclical" },
    { symbol: "EXR", name: "Extra Space Storage Inc", sector: "Real Estate" },
    { symbol: "F", name: "Ford Motor Company", sector: "Consumer Cyclical" },
    { symbol: "FANG", name: "Diamondback Energy, Inc.", sector: "Energy" },
    { symbol: "FAST", name: "Fastenal Company", sector: "Industrials" },
    { symbol: "FCX", name: "Freeport-McMoRan, Inc.", sector: "Basic Materials" },
    { symbol: "FDS", name: "FactSet Research Systems Inc.", sector: "Financial Services" },
    { symbol: "FDX", name: "FedEx Corporation", sector: "Industrials" },
    { symbol: "FE", name: "FirstEnergy Corp.", sector: "Utilities" },
    { symbol: "FFIV", name: "F5, Inc.", sector: "Technology" },
    { symbol: "FI", name: "Fiserv, Inc.", sector: "Technology" },
    { symbol: "FICO", name: "Fair Isaac Corporation", sector: "Technology" },
    { symbol: "FIS", name: "Fidelity National Information S", sector: "Technology" },
    { symbol: "FITB", name: "Fifth Third Bancorp", sector: "Financial Services" },
    { symbol: "FMC", name: "FMC Corporation", sector: "Basic Materials" },
    { symbol: "FOX", name: "Fox Corporation", sector: "Communication Services" },
    { symbol: "FOXA", name: "Fox Corporation", sector: "Communication Services" },
    { symbol: "FRT", name: "Federal Realty Investment Trust", sector: "Real Estate" },
    { symbol: "FSLR", name: "First Solar, Inc.", sector: "Technology" },
    { symbol: "FTNT", name: "Fortinet, Inc.", sector: "Technology" },
    { symbol: "FTV", name: "Fortive Corporation", sector: "Technology" },
    { symbol: "GD", name: "General Dynamics Corporation", sector: "Industrials" },
    { symbol: "GDDY", name: "GoDaddy Inc.", sector: "Technology" },
    { symbol: "GE", name: "GE Aerospace", sector: "Industrials" },
    { symbol: "GEHC", name: "GE HealthCare Technologies Inc.", sector: "Healthcare" },
    { symbol: "GEN", name: "Gen Digital Inc.", sector: "Technology" },
    { symbol: "GEV", name: "GE Vernova Inc.", sector: "Utilities" },
    { symbol: "GILD", name: "Gilead Sciences, Inc.", sector: "Healthcare" },
    { symbol: "GIS", name: "General Mills, Inc.", sector: "Consumer Defensive" },
    { symbol: "GL", name: "Globe Life Inc.", sector: "Financial Services" },
    { symbol: "GLW", name: "Corning Incorporated", sector: "Technology" },
    { symbol: "GM", name: "General Motors Company", sector: "Consumer Cyclical" },
    { symbol: "GNRC", name: "Generac Holdlings Inc.", sector: "Industrials" },
    { symbol: "GOOG", name: "Alphabet Inc.", sector: "Communication Services" },
    { symbol: "GOOGL", name: "Alphabet Inc.", sector: "Communication Services" },
    { symbol: "GPC", name: "Genuine Parts Company", sector: "Consumer Cyclical" },
    { symbol: "GPN", name: "Global Payments Inc.", sector: "Industrials" },
    { symbol: "GRMN", name: "Garmin Ltd.", sector: "Technology" },
    { symbol: "GS", name: "Goldman Sachs Group, Inc. (The)", sector: "Financial Services" },
    { symbol: "GWW", name: "W.W. Grainger, Inc.", sector: "Industrials" },
    { symbol: "HAL", name: "Halliburton Company", sector: "Energy" },
    { symbol: "HAS", name: "Hasbro, Inc.", sector: "Consumer Cyclical" },
    { symbol: "HBAN", name: "Huntington Bancshares Incorpora", sector: "Financial Services" },
    { symbol: "HCA", name: "HCA Healthcare, Inc.", sector: "Healthcare" },
    { symbol: "HD", name: "Home Depot, Inc. (The)", sector: "Consumer Cyclical" },
    { symbol: "HES", name: "Hess Corporation", sector: "Energy" },
    { symbol: "HIG", name: "Hartford Financial Services Gro", sector: "Financial Services" },
    { symbol: "HII", name: "Huntington Ingalls Industries, ", sector: "Industrials" },
    { symbol: "HLT", name: "Hilton Worldwide Holdings Inc.", sector: "Consumer Cyclical" },
    { symbol: "HOLX", name: "Hologic, Inc.", sector: "Healthcare" },
    { symbol: "HON", name: "Honeywell International Inc.", sector: "Industrials" },
    { symbol: "HPE", name: "Hewlett Packard Enterprise Comp", sector: "Technology" },
    { symbol: "HPQ", name: "HP Inc.", sector: "Technology" },
    { symbol: "HRL", name: "Hormel Foods Corporation", sector: "Consumer Defensive" },
    { symbol: "HSIC", name: "Henry Schein, Inc.", sector: "Healthcare" },
    { symbol: "HST", name: "Host Hotels & Resorts, Inc.", sector: "Real Estate" },
    { symbol: "HSY", name: "The Hershey Company", sector: "Consumer Defensive" },
    { symbol: "HUBB", name: "Hubbell Inc", sector: "Industrials" },
    { symbol: "HUM", name: "Humana Inc.", sector: "Healthcare" },
    { symbol: "HWM", name: "Howmet Aerospace Inc.", sector: "Industrials" },
    { symbol: "IBM", name: "International Business Machines", sector: "Technology" },
    { symbol: "ICE", name: "Intercontinental Exchange Inc.", sector: "Financial Services" },
    { symbol: "IDXX", name: "IDEXX Laboratories, Inc.", sector: "Healthcare" },
    { symbol: "IEX", name: "IDEX Corporation", sector: "Industrials" },
    { symbol: "IFF", name: "International Flavors & Fragran", sector: "Basic Materials" },
    { symbol: "INCY", name: "Incyte Corporation", sector: "Healthcare" },
    { symbol: "INTC", name: "Intel Corporation", sector: "Technology" },
    { symbol: "INTU", name: "Intuit Inc.", sector: "Technology" },
    { symbol: "INVH", name: "Invitation Homes Inc.", sector: "Real Estate" },
    { symbol: "IP", name: "International Paper Company", sector: "Consumer Cyclical" },
    { symbol: "IPG", name: "Interpublic Group of Companies,", sector: "Communication Services" },
    { symbol: "IQV", name: "IQVIA Holdings, Inc.", sector: "Healthcare" },
    { symbol: "IR", name: "Ingersoll Rand Inc.", sector: "Industrials" },
    { symbol: "IRM", name: "Iron Mountain Incorporated (Del", sector: "Real Estate" },
    { symbol: "ISRG", name: "Intuitive Surgical, Inc.", sector: "Healthcare" },
    { symbol: "IT", name: "Gartner, Inc.", sector: "Technology" },
    { symbol: "ITW", name: "Illinois Tool Works Inc.", sector: "Industrials" },
    { symbol: "IVZ", name: "Invesco Ltd", sector: "Financial Services" },
    { symbol: "J", name: "Jacobs Solutions Inc.", sector: "Industrials" },
    { symbol: "JBHT", name: "J.B. Hunt Transport Services, I", sector: "Industrials" },
    { symbol: "JBL", name: "Jabil Inc.", sector: "Technology" },
    { symbol: "JCI", name: "Johnson Controls International ", sector: "Industrials" },
    { symbol: "JKHY", name: "Jack Henry & Associates, Inc.", sector: "Technology" },
    { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
    { symbol: "JNPR", name: "Juniper Networks, Inc.", sector: "Technology" },
    { symbol: "JPM", name: "JP Morgan Chase & Co.", sector: "Financial Services" },
    { symbol: "K", name: "Kellanova", sector: "Consumer Defensive" },
    { symbol: "KDP", name: "Keurig Dr Pepper Inc.", sector: "Consumer Defensive" },
    { symbol: "KEY", name: "KeyCorp", sector: "Financial Services" },
    { symbol: "KEYS", name: "Keysight Technologies Inc.", sector: "Technology" },
    { symbol: "KHC", name: "The Kraft Heinz Company", sector: "Consumer Defensive" },
    { symbol: "KIM", name: "Kimco Realty Corporation (HC)", sector: "Real Estate" },
    { symbol: "KKR", name: "KKR & Co. Inc.", sector: "Financial Services" },
    { symbol: "KLAC", name: "KLA Corporation", sector: "Technology" },
    { symbol: "KMB", name: "Kimberly-Clark Corporation", sector: "Consumer Defensive" },
    { symbol: "KMI", name: "Kinder Morgan, Inc.", sector: "Energy" },
    { symbol: "KMX", name: "CarMax Inc", sector: "Consumer Cyclical" },
    { symbol: "KO", name: "Coca-Cola Company (The)", sector: "Consumer Defensive" },
    { symbol: "KR", name: "Kroger Company (The)", sector: "Consumer Defensive" },
    { symbol: "KVUE", name: "Kenvue Inc.", sector: "Consumer Defensive" },
    { symbol: "L", name: "Loews Corporation", sector: "Financial Services" },
    { symbol: "LDOS", name: "Leidos Holdings, Inc.", sector: "Technology" },
    { symbol: "LEN", name: "Lennar Corporation", sector: "Consumer Cyclical" },
    { symbol: "LH", name: "Labcorp Holdings Inc.", sector: "Healthcare" },
    { symbol: "LHX", name: "L3Harris Technologies, Inc.", sector: "Industrials" },
    { symbol: "LIN", name: "Linde plc", sector: "Basic Materials" },
    { symbol: "LKQ", name: "LKQ Corporation", sector: "Consumer Cyclical" },
    { symbol: "LLY", name: "Eli Lilly and Company", sector: "Healthcare" },
    { symbol: "LMT", name: "Lockheed Martin Corporation", sector: "Industrials" },
    { symbol: "LNT", name: "Alliant Energy Corporation", sector: "Utilities" },
    { symbol: "LOW", name: "Lowe's Companies, Inc.", sector: "Consumer Cyclical" },
    { symbol: "LRCX", name: "Lam Research Corporation", sector: "Technology" },
    { symbol: "LULU", name: "lululemon athletica inc.", sector: "Consumer Cyclical" },
    { symbol: "LUV", name: "Southwest Airlines Company", sector: "Industrials" },
    { symbol: "LVS", name: "Las Vegas Sands Corp.", sector: "Consumer Cyclical" },
    { symbol: "LW", name: "Lamb Weston Holdings, Inc.", sector: "Consumer Defensive" },
    { symbol: "LYB", name: "LyondellBasell Industries NV", sector: "Basic Materials" },
    { symbol: "LYV", name: "Live Nation Entertainment, Inc.", sector: "Communication Services" },
    { symbol: "MA", name: "Mastercard Incorporated", sector: "Financial Services" },
    { symbol: "MAA", name: "Mid-America Apartment Communiti", sector: "Real Estate" },
    { symbol: "MAR", name: "Marriott International", sector: "Consumer Cyclical" },
    { symbol: "MAS", name: "Masco Corporation", sector: "Industrials" },
    { symbol: "MCD", name: "McDonald's Corporation", sector: "Consumer Cyclical" },
    { symbol: "MCHP", name: "Microchip Technology Incorporat", sector: "Technology" },
    { symbol: "MCK", name: "McKesson Corporation", sector: "Healthcare" },
    { symbol: "MCO", name: "Moody's Corporation", sector: "Financial Services" },
    { symbol: "MDLZ", name: "Mondelez International, Inc.", sector: "Consumer Defensive" },
    { symbol: "MDT", name: "Medtronic plc.", sector: "Healthcare" },
    { symbol: "MET", name: "MetLife, Inc.", sector: "Financial Services" },
    { symbol: "META", name: "Meta Platforms, Inc.", sector: "Communication Services" },
    { symbol: "MGM", name: "MGM Resorts International", sector: "Consumer Cyclical" },
    { symbol: "MHK", name: "Mohawk Industries, Inc.", sector: "Consumer Cyclical" },
    { symbol: "MKC", name: "McCormick & Company, Incorporat", sector: "Consumer Defensive" },
    { symbol: "MKTX", name: "MarketAxess Holdings, Inc.", sector: "Financial Services" },
    { symbol: "MLM", name: "Martin Marietta Materials, Inc.", sector: "Basic Materials" },
    { symbol: "MMC", name: "Marsh & McLennan Companies, Inc", sector: "Financial Services" },
    { symbol: "MMM", name: "3M Company", sector: "Industrials" },
    { symbol: "MNST", name: "Monster Beverage Corporation", sector: "Consumer Defensive" },
    { symbol: "MO", name: "Altria Group, Inc.", sector: "Consumer Defensive" },
    { symbol: "MOH", name: "Molina Healthcare Inc", sector: "Healthcare" },
    { symbol: "MOS", name: "Mosaic Company (The)", sector: "Basic Materials" },
    { symbol: "MPC", name: "Marathon Petroleum Corporation", sector: "Energy" },
    { symbol: "MPWR", name: "Monolithic Power Systems, Inc.", sector: "Technology" },
    { symbol: "MRK", name: "Merck & Company, Inc.", sector: "Healthcare" },
    { symbol: "MRNA", name: "Moderna, Inc.", sector: "Healthcare" },
    { symbol: "MS", name: "Morgan Stanley", sector: "Financial Services" },
    { symbol: "MSCI", name: "MSCI Inc.", sector: "Financial Services" },
    { symbol: "MSFT", name: "Microsoft Corporation", sector: "Technology" },
    { symbol: "MSI", name: "Motorola Solutions, Inc.", sector: "Technology" },
    { symbol: "MTB", name: "M&T Bank Corporation", sector: "Financial Services" },
    { symbol: "MTCH", name: "Match Group, Inc.", sector: "Communication Services" },
    { symbol: "MTD", name: "Mettler-Toledo International, I", sector: "Healthcare" },
    { symbol: "MU", name: "Micron Technology, Inc.", sector: "Technology" },
    { symbol: "NCLH", name: "Norwegian Cruise Line Holdings ", sector: "Consumer Cyclical" },
    { symbol: "NDAQ", name: "Nasdaq, Inc.", sector: "Financial Services" },
    { symbol: "NDSN", name: "Nordson Corporation", sector: "Industrials" },
    { symbol: "NEE", name: "NextEra Energy, Inc.", sector: "Utilities" },
    { symbol: "NEM", name: "Newmont Corporation", sector: "Basic Materials" },
    { symbol: "NFLX", name: "Netflix, Inc.", sector: "Communication Services" },
    { symbol: "NI", name: "NiSource Inc", sector: "Utilities" },
    { symbol: "NKE", name: "Nike, Inc.", sector: "Consumer Cyclical" },
    { symbol: "NOC", name: "Northrop Grumman Corporation", sector: "Industrials" },
    { symbol: "NOW", name: "ServiceNow, Inc.", sector: "Technology" },
    { symbol: "NRG", name: "NRG Energy, Inc.", sector: "Utilities" },
    { symbol: "NSC", name: "Norfolk Southern Corporation", sector: "Industrials" },
    { symbol: "NTAP", name: "NetApp, Inc.", sector: "Technology" },
    { symbol: "NTRS", name: "Northern Trust Corporation", sector: "Financial Services" },
    { symbol: "NUE", name: "Nucor Corporation", sector: "Basic Materials" },
    { symbol: "NVDA", name: "NVIDIA Corporation", sector: "Technology" },
    { symbol: "NVR", name: "NVR, Inc.", sector: "Consumer Cyclical" },
    { symbol: "NWS", name: "News Corporation", sector: "Communication Services" },
    { symbol: "NWSA", name: "News Corporation", sector: "Communication Services" },
    { symbol: "NXPI", name: "NXP Semiconductors N.V.", sector: "Technology" },
    { symbol: "O", name: "Realty Income Corporation", sector: "Real Estate" },
    { symbol: "ODFL", name: "Old Dominion Freight Line, Inc.", sector: "Industrials" },
    { symbol: "OKE", name: "ONEOK, Inc.", sector: "Energy" },
    { symbol: "OMC", name: "Omnicom Group Inc.", sector: "Communication Services" },
    { symbol: "ON", name: "ON Semiconductor Corporation", sector: "Technology" },
    { symbol: "ORCL", name: "Oracle Corporation", sector: "Technology" },
    { symbol: "ORLY", name: "O'Reilly Automotive, Inc.", sector: "Consumer Cyclical" },
    { symbol: "OTIS", name: "Otis Worldwide Corporation", sector: "Industrials" },
    { symbol: "OXY", name: "Occidental Petroleum Corporatio", sector: "Energy" },
    { symbol: "PANW", name: "Palo Alto Networks, Inc.", sector: "Technology" },
    { symbol: "PARA", name: "Paramount Global", sector: "Communication Services" },
    { symbol: "PAYC", name: "Paycom Software, Inc.", sector: "Technology" },
    { symbol: "PAYX", name: "Paychex, Inc.", sector: "Technology" },
    { symbol: "PCAR", name: "PACCAR Inc.", sector: "Industrials" },
    { symbol: "PCG", name: "Pacific Gas & Electric Co.", sector: "Utilities" },
    { symbol: "PEG", name: "Public Service Enterprise Group", sector: "Utilities" },
    { symbol: "PEP", name: "Pepsico, Inc.", sector: "Consumer Defensive" },
    { symbol: "PFE", name: "Pfizer, Inc.", sector: "Healthcare" },
    { symbol: "PFG", name: "Principal Financial Group Inc", sector: "Financial Services" },
    { symbol: "PG", name: "Procter & Gamble Company (The)", sector: "Consumer Defensive" },
    { symbol: "PGR", name: "Progressive Corporation (The)", sector: "Financial Services" },
    { symbol: "PH", name: "Parker-Hannifin Corporation", sector: "Industrials" },
    { symbol: "PHM", name: "PulteGroup, Inc.", sector: "Consumer Cyclical" },
    { symbol: "PKG", name: "Packaging Corporation of Americ", sector: "Consumer Cyclical" },
    { symbol: "PLD", name: "Prologis, Inc.", sector: "Real Estate" },
    { symbol: "PLTR", name: "Palantir Technologies Inc.", sector: "Technology" },
    { symbol: "PM", name: "Philip Morris International Inc", sector: "Consumer Defensive" },
    { symbol: "PNC", name: "PNC Financial Services Group, I", sector: "Financial Services" },
    { symbol: "PNR", name: "Pentair plc.", sector: "Industrials" },
    { symbol: "PNW", name: "Pinnacle West Capital Corporati", sector: "Utilities" },
    { symbol: "PODD", name: "Insulet Corporation", sector: "Healthcare" },
    { symbol: "POOL", name: "Pool Corporation", sector: "Industrials" },
    { symbol: "PPG", name: "PPG Industries, Inc.", sector: "Basic Materials" },
    { symbol: "PPL", name: "PPL Corporation", sector: "Utilities" },
    { symbol: "PRU", name: "Prudential Financial, Inc.", sector: "Financial Services" },
    { symbol: "PSA", name: "Public Storage", sector: "Real Estate" },
    { symbol: "PSX", name: "Phillips 66", sector: "Energy" },
    { symbol: "PTC", name: "PTC Inc.", sector: "Technology" },
    { symbol: "PWR", name: "Quanta Services, Inc.", sector: "Industrials" },
    { symbol: "PYPL", name: "PayPal Holdings, Inc.", sector: "Financial Services" },
    { symbol: "QCOM", name: "QUALCOMM Incorporated", sector: "Technology" },
    { symbol: "QRVO", name: "Qorvo, Inc.", sector: "Technology" },
    { symbol: "RCL", name: "Royal Caribbean Cruises Ltd.", sector: "Consumer Cyclical" },
    { symbol: "REG", name: "Regency Centers Corporation", sector: "Real Estate" },
    { symbol: "REGN", name: "Regeneron Pharmaceuticals, Inc.", sector: "Healthcare" },
    { symbol: "RF", name: "Regions Financial Corporation", sector: "Financial Services" },
    { symbol: "RJF", name: "Raymond James Financial, Inc.", sector: "Financial Services" },
    { symbol: "RL", name: "Ralph Lauren Corporation", sector: "Consumer Cyclical" },
    { symbol: "RMD", name: "ResMed Inc.", sector: "Healthcare" },
    { symbol: "ROK", name: "Rockwell Automation, Inc.", sector: "Industrials" },
    { symbol: "ROL", name: "Rollins, Inc.", sector: "Consumer Cyclical" },
    { symbol: "ROP", name: "Roper Technologies, Inc.", sector: "Technology" },
    { symbol: "ROST", name: "Ross Stores, Inc.", sector: "Consumer Cyclical" },
    { symbol: "RSG", name: "Republic Services, Inc.", sector: "Industrials" },
    { symbol: "RTX", name: "RTX Corporation", sector: "Industrials" },
    { symbol: "RVTY", name: "Revvity, Inc.", sector: "Healthcare" },
    { symbol: "SBAC", name: "SBA Communications Corporation", sector: "Real Estate" },
    { symbol: "SBUX", name: "Starbucks Corporation", sector: "Consumer Cyclical" },
    { symbol: "SCHW", name: "Charles Schwab Corporation (The", sector: "Financial Services" },
    { symbol: "SHW", name: "Sherwin-Williams Company (The)", sector: "Basic Materials" },
    { symbol: "SJM", name: "The J.M. Smucker Company", sector: "Consumer Defensive" },
    { symbol: "SLB", name: "Schlumberger N.V.", sector: "Energy" },
    { symbol: "SMCI", name: "Super Micro Computer, Inc.", sector: "Technology" },
    { symbol: "SNA", name: "Snap-On Incorporated", sector: "Industrials" },
    { symbol: "SNPS", name: "Synopsys, Inc.", sector: "Technology" },
    { symbol: "SO", name: "Southern Company (The)", sector: "Utilities" },
    { symbol: "SOLV", name: "Solventum Corporation", sector: "Healthcare" },
    { symbol: "SPG", name: "Simon Property Group, Inc.", sector: "Real Estate" },
    { symbol: "SPGI", name: "S&P Global Inc.", sector: "Financial Services" },
    { symbol: "SRE", name: "DBA Sempra", sector: "Utilities" },
    { symbol: "STE", name: "STERIS plc (Ireland)", sector: "Healthcare" },
    { symbol: "STLD", name: "Steel Dynamics, Inc.", sector: "Basic Materials" },
    { symbol: "STT", name: "State Street Corporation", sector: "Financial Services" },
    { symbol: "STX", name: "Seagate Technology Holdings PLC", sector: "Technology" },
    { symbol: "STZ", name: "Constellation Brands, Inc.", sector: "Consumer Defensive" },
    { symbol: "SW", name: "Smurfit WestRock plc", sector: "Consumer Cyclical" },
    { symbol: "SWK", name: "Stanley Black & Decker, Inc.", sector: "Industrials" },
    { symbol: "SWKS", name: "Skyworks Solutions, Inc.", sector: "Technology" },
    { symbol: "SYF", name: "Synchrony Financial", sector: "Financial Services" },
    { symbol: "SYK", name: "Stryker Corporation", sector: "Healthcare" },
    { symbol: "SYY", name: "Sysco Corporation", sector: "Consumer Defensive" },
    { symbol: "T", name: "AT&T Inc.", sector: "Communication Services" },
    { symbol: "TAP", name: "Molson Coors Beverage Company", sector: "Consumer Defensive" },
    { symbol: "TDG", name: "Transdigm Group Incorporated", sector: "Industrials" },
    { symbol: "TDY", name: "Teledyne Technologies Incorpora", sector: "Technology" },
    { symbol: "TECH", name: "Bio-Techne Corp", sector: "Healthcare" },
    { symbol: "TEL", name: "TE Connectivity plc", sector: "Technology" },
    { symbol: "TER", name: "Teradyne, Inc.", sector: "Technology" },
    { symbol: "TFC", name: "Truist Financial Corporation", sector: "Financial Services" },
    { symbol: "TFX", name: "Teleflex Incorporated", sector: "Healthcare" },
    { symbol: "TGT", name: "Target Corporation", sector: "Consumer Defensive" },
    { symbol: "TJX", name: "TJX Companies, Inc. (The)", sector: "Consumer Cyclical" },
    { symbol: "TMO", name: "Thermo Fisher Scientific Inc", sector: "Healthcare" },
    { symbol: "TMUS", name: "T-Mobile US, Inc.", sector: "Communication Services" },
    { symbol: "TPL", name: "Texas Pacific Land Corporation", sector: "Energy" },
    { symbol: "TPR", name: "Tapestry, Inc.", sector: "Consumer Cyclical" },
    { symbol: "TRGP", name: "Targa Resources, Inc.", sector: "Energy" },
    { symbol: "TRMB", name: "Trimble Inc.", sector: "Technology" },
    { symbol: "TROW", name: "T. Rowe Price Group, Inc.", sector: "Financial Services" },
    { symbol: "TRV", name: "The Travelers Companies, Inc.", sector: "Financial Services" },
    { symbol: "TSCO", name: "Tractor Supply Company", sector: "Consumer Cyclical" },
    { symbol: "TSLA", name: "Tesla, Inc.", sector: "Consumer Cyclical" },
    { symbol: "TSN", name: "Tyson Foods, Inc.", sector: "Consumer Defensive" },
    { symbol: "TT", name: "Trane Technologies plc", sector: "Industrials" },
    { symbol: "TTWO", name: "Take-Two Interactive Software, ", sector: "Communication Services" },
    { symbol: "TXN", name: "Texas Instruments Incorporated", sector: "Technology" },
    { symbol: "TXT", name: "Textron Inc.", sector: "Industrials" },
    { symbol: "TYL", name: "Tyler Technologies, Inc.", sector: "Technology" },
    { symbol: "UAL", name: "United Airlines Holdings, Inc.", sector: "Industrials" },
    { symbol: "UBER", name: "Uber Technologies, Inc.", sector: "Technology" },
    { symbol: "UDR", name: "UDR, Inc.", sector: "Real Estate" },
    { symbol: "UHS", name: "Universal Health Services, Inc.", sector: "Healthcare" },
    { symbol: "ULTA", name: "Ulta Beauty, Inc.", sector: "Consumer Cyclical" },
    { symbol: "UNH", name: "UnitedHealth Group Incorporated", sector: "Healthcare" },
    { symbol: "UNP", name: "Union Pacific Corporation", sector: "Industrials" },
    { symbol: "UPS", name: "United Parcel Service, Inc.", sector: "Industrials" },
    { symbol: "URI", name: "United Rentals, Inc.", sector: "Industrials" },
    { symbol: "USB", name: "U.S. Bancorp", sector: "Financial Services" },
    { symbol: "V", name: "Visa Inc.", sector: "Financial Services" },
    { symbol: "VICI", name: "VICI Properties Inc.", sector: "Real Estate" },
    { symbol: "VLO", name: "Valero Energy Corporation", sector: "Energy" },
    { symbol: "VLTO", name: "Veralto Corp", sector: "Industrials" },
    { symbol: "VMC", name: "Vulcan Materials Company (Holdi", sector: "Basic Materials" },
    { symbol: "VRSK", name: "Verisk Analytics, Inc.", sector: "Industrials" },
    { symbol: "VRSN", name: "VeriSign, Inc.", sector: "Technology" },
    { symbol: "VRTX", name: "Vertex Pharmaceuticals Incorpor", sector: "Healthcare" },
    { symbol: "VST", name: "Vistra Corp.", sector: "Utilities" },
    { symbol: "VTR", name: "Ventas, Inc.", sector: "Real Estate" },
    { symbol: "VTRS", name: "Viatris Inc.", sector: "Healthcare" },
    { symbol: "VZ", name: "Verizon Communications Inc.", sector: "Communication Services" },
    { symbol: "WAB", name: "Westinghouse Air Brake Technolo", sector: "Industrials" },
    { symbol: "WAT", name: "Waters Corporation", sector: "Healthcare" },
    { symbol: "WBA", name: "Walgreens Boots Alliance, Inc.", sector: "Healthcare" },
    { symbol: "WBD", name: "Warner Bros. Discovery, Inc. - ", sector: "Communication Services" },
    { symbol: "WDC", name: "Western Digital Corporation", sector: "Technology" },
    { symbol: "WEC", name: "WEC Energy Group, Inc.", sector: "Utilities" },
    { symbol: "WELL", name: "Welltower Inc.", sector: "Real Estate" },
    { symbol: "WFC", name: "Wells Fargo & Company", sector: "Financial Services" },
    { symbol: "WM", name: "Waste Management, Inc.", sector: "Industrials" },
    { symbol: "WMB", name: "Williams Companies, Inc. (The)", sector: "Energy" },
    { symbol: "WMT", name: "Walmart Inc.", sector: "Consumer Defensive" },
    { symbol: "WRB", name: "W.R. Berkley Corporation", sector: "Financial Services" },
    { symbol: "WST", name: "West Pharmaceutical Services, I", sector: "Healthcare" },
    { symbol: "WTW", name: "Willis Towers Watson Public Lim", sector: "Financial Services" },
    { symbol: "WY", name: "Weyerhaeuser Company", sector: "Real Estate" },
    { symbol: "WYNN", name: "Wynn Resorts, Limited", sector: "Consumer Cyclical" },
    { symbol: "XEL", name: "Xcel Energy Inc.", sector: "Utilities" },
    { symbol: "XOM", name: "Exxon Mobil Corporation", sector: "Energy" },
    { symbol: "XYL", name: "Xylem Inc.", sector: "Industrials" },
    { symbol: "YUM", name: "Yum! Brands, Inc.", sector: "Consumer Cyclical" },
    { symbol: "ZBH", name: "Zimmer Biomet Holdings, Inc.", sector: "Healthcare" },
    { symbol: "ZBRA", name: "Zebra Technologies Corporation", sector: "Technology" },
    { symbol: "ZTS", name: "Zoetis Inc.", sector: "Healthcare" }
];
